### ISSUE TITLE
🐛 Bug Report — WebSockets are broken inside Durable Object `blockConcurrencyWhile`

### ISSUE THREAD

**Issue by TimoWilhelm** [cloudflare/workerd#1088]
I'm tryling to use a [WebSocket-based PG Proxy](https://github.com/neondatabase/serverless) in my Durable Object. During DO initialization I'm querying some data. However all WebSocket connections seem to fail in the `blockConcurrencyWhile` guard.

I've created a minimal, reproducible example here https://github.com/TimoWilhelm/mre-do-websocket-constructor.

The `/fetch` route will instantiate a WebSocket, wait for a message and return.
This works as expected.

For the `/do` route the same WebSocket code is run in the `state.blockConcurrencyWhile` guard in the Durable Object constructor.
However, this WebSocket connection will never recieve a message. This will lead to the following error when the request is made:
`Error: A call to blockConcurrencyWhile() in a Durable Object waited for too long. The call was canceled and the Durable Object was reset.`

# Environment
compatibility_date = "2023-08-15"
Tested on Wrangler + CF

**Comment by kentonv** [comment]
I think to fix this, the `WebSocket` API needs to capture the current `InputGate::CriticalSection` when it is created, and then `WebSocket::readLoop()` needs to provide this critical section when calling `context.run`. Otherwise, each message that arrives is treated like a new independent event, and is thus blocked until the `blockConcurrencyWhile()` finishes.

I think @MellowYarker is the expert at this code these days, although I think this bug probably predates him joining the project.
