### ISSUE TITLE
I would like to opt-out of js context reuse for durable objects.

### ISSUE THREAD

**Issue by aboodman** [cloudflare/workerd#1186]
JS contexts can be reused in some cases across DO instances. For example, if one calls `wrangler tail` while a DO is running, it is unloaded and a new instance is loaded into the same JS context.

This behavior is very confusing because it breaks the semantics of global variables. We try to avoid globals, but they are sometimes useful or unavoidable. Here are a few cases where we have struggled with this in our applications:

1. We have accidentally written code that wasn't safe to use in workers. Although we have been careful to try to avoid globals since learning of this behavior, we still managed to accidentally put a lock in a global variable. Someone wrote `const foo = new Thing()` and forgot that deep inside `Thing` there was a lock. Due to reloading js contexts (together with #1185), this lock never got released and our DO stopped responding to requests.
2. We have had to carefully scrutinize third party libraries, even if they are pure JS, to look at how they use globals.
3. We run third-party code in workers via WfP. We have to carefully design our APIs and document things to ensure our customers don't use global variables.
4. We want to override the behavior of console.log to stream logs to a logging aggregator. To do so would require replacing `console.log` with some function. We would then have to be very careful to consider what happens when the context is reloaded and this function is set multiple times. This is a general problem with polyfilling, a common practice of JavaScript programmers.

We have at this point spent person-weeks on issues stemming from JS Contexts getting reloaded and it's not a feature we want. Our DOs are long-lived and we are happy to spend an extra few ms on start in some edge cases to ensure we always get a fresh context.

For these reasons, t would be great to be able to opt-out of reusing JS contexts in DOs.

**Comment by aboodman** [comment]
We were confused about what we were seeing here. This bug is invalid. We thought we were seeing code getting loaded into a context twice.

**Comment by kentonv** [comment]
Right, the code is only loaded once. It's only that multiple instances of your DO class can be created in the context, once the code is loaded. This typically only happens if you have a lot of DOs -- the goal is to be able to support applications with billions of small DOs by minimizing the marginal overhead of each one.

We could let you opt out of multiple DOs sharing an isolate, with the caveat that this may set a much lower ceiling on the total number of live DOs you can have at once.

FWIW we are working towards a future where every DO and even every request (outside of DOs) will appear as if they run in a private isolate, using copy-on-write magic, but it's going to be a big project to make this efficient.

**Comment by aboodman** [comment]
> This typically only happens if you have a lot of DOs

FYI, you can also reliably cause this situation by invoking `npx wrangler tail` on the CLI, or by doing `npx wrangler publish` with no changes to the code.

**Comment by aboodman** [comment]
> FWIW we are working towards a future where every DO and even every request (outside of DOs) will appear as if they run in a private isolate, using copy-on-write magic, but it's going to be a big project to make this efficient.

That sounds very cool.
