### ISSUE TITLE
`Response` from worker-types is incompatible with `Response` from TypeScript

### ISSUE THREAD

**Issue by dr-vortex** [cloudflare/workerd#1383]
When trying to use the non-cloudflare `Response`, Typescript gives a number of errors.

For example (pages function):
```ts
export const onRequest: PagesFunction = async (context): Promise<Response> => {
// ...
}
```

First error:
```ts
Type '(context: EventContext<unknown, any, Record<string, unknown>>) => Promise<Response>' is not assignable to type 'PagesFunction'.
  Type 'Promise<Response>' is not assignable to type 'Response | Promise<Response>'.
    Type 'Promise<Response>' is not assignable to type 'Promise<import("node_modules/@cloudflare/workers-types/index").Response>'.
      Property 'webSocket' is missing in type 'Response' but required in type 'import("node_modules/@cloudflare/workers-types/index").Response'.ts(2322)
```

Which can be fixed: 
`node_modules/@cloudflare/workers-types/index` > `Request`
```diff
  readonly redirected: boolean;
  readonly url: string;
-  readonly webSocket: WebSocket | null;
+  readonly webSocket?: WebSocket;
  readonly cf?: any;
}
```

**Comment by penalosa** [comment]
This is intentional. The types for `@cloudflare/workers-types` are generated directly from the workers runtime implementation, and so accurately match runtime behaviour. In most cases we're pretty close to spec-compliant with web standards, and so are similar to `lib.dom.d.ts`, but we recommend using `@cloudflare/workers-types` exclusively, and not typing your codebase against `lib.dom.d.ts`.

**Comment by aaronadamsCA** [comment]
@penalosa, I just found this issue from a few months ago.

I wanted to switch to imported types [as described in the package docs](https://www.npmjs.com/package/@cloudflare/workers-types#importable-types), but even a simple "hello world" app results in a type mismatch:

https://stackblitz.com/edit/cloudflare-workers-sdk-wzwkvq?file=src%2Findex.ts

Do you know if there's a solution to this?

**Comment by uncenter** [comment]
Any updates? Also curious why a very basic app doesn't work correctly with the types. Thanks!

**Comment by penalosa** [comment]
In general, I'd recommend using `@cloudflare/workers-types` by setting the `types` property in your `tsconfig.json` file. The importable types are provided for fairly niche use-cases (primarily for library authors), and for most applications you'll have a better experience if you use `@cloudflare/workers-types` exclusively, with no interference from lib dom or undici. 

@aaronadamsCA in your specific example, it looks like the `Response` type is coming from a package called `undici-types`—I'm not sure if that's something Stackblitz installs by default?

If it's absolutely necessary that you typecheck your app in a DOM context rather than a `@cloudflare/workers-types` context, you should be _mostly_ fine as long as you stay away from types like `ExportedHandler`:

```ts
export default {
  async fetch(request: Request): Promise<Response> {
    return new Response("Hello World!");
  },
};
```

However, this is definitely not recommended, and could end up with your app behaving differently to how you'd expect at runtime. As just one example, the `webSocket` property on the `Response` class is a non-standard Cloudflare extension that won't typecheck properly in a DOM context: 
```ts
return new Response(null, {
  status: 101,
  webSocket: client,
});
```

**Comment by WesleyYue** [comment]
@penalosa it's not a stackblitz specific issue. I get the same problem on my local vscode. It's from `@types/node` (https://github.com/DefinitelyTyped/DefinitelyTyped/blob/c58e3459ea3d434ca1e7bf3a0e1ffcb4a95d363b/types/node/globals.d.ts#L389)

What's unclear to me is why the TS server imports @types/node

**Comment by WesleyYue** [comment]
There are 2 different causes:
For the StackBlitz example, specifying tsconfig to use cloudflare types fixes it
```json
...
		"types": [
			"@cloudflare/workers-types/2023-07-01"
		] /* Specify type package names to be included without being referenced in a source file. */,
...
```

For my issue, I already had this in tsconfig, but `npm create cloudflare@latest` with the typescript option automatically creates `vitest.config.js` which imports `@cloudflare/vitest-pool-workers/config` ([here](https://developers.cloudflare.com/workers/testing/vitest-integration/configuration/)) which imports `@types/node` to my global types and TS is unable to distinguish the two

**Comment by juane1000** [comment]
Running into this issue as well on a fresh "npm create cloudflare@latest". @WesleyYue that makes a lot of sense. Did you workaround it?

**Comment by WesleyYue** [comment]
It's been a while since I wrote that comment so I have completely forgotten what I did, but just re-reading my comment I think the answer is just import the types?

https://www.npmjs.com/package/@cloudflare/workers-types#importable-types
