### ISSUE TITLE
🐛 BUG: warning always received about multiple bind addresses

### ISSUE THREAD

**Issue by Cherry** [cloudflare/workerd#1408]
### Which Cloudflare product(s) does this pertain to?

Wrangler core

### What version(s) of the tool(s) are you using?

3.8.0

### What version of Node are you using?

18.17.1

### What operating system are you using?

Windows 10

### Describe the Bug

Every time that you start `wrangler dev`, you get a large red error like so (from `workerd` it would seem):
![](https://up.jross.me/l6zknlju)

```
kj/async-io-win32.c++:982: warning: Bind address resolved to multiple addresses.  Only the first address will be used.  If this is incorrect, specify the address numerically.  This may be fixed in the future.; addrs[0].toString() = 127.0.0.1:59208
```

It's possible that this only occurs in Windows, or when a machine has multiple network adapters. Hitting `b` still works fine, and opening up `http://127.0.0.1:8787/` is fine too, so perhaps the error should just be hidden?

## Reproduction steps

- npm create cloudflare@latest
- use all defaults
- `cd` into worker dir and run `npm start`

**Comment by kentonv** [comment]
I suspect this is because `localhost` maps to two addresses -- one ipv4 and one ipv6.

This isn't a big deal in practice because everything trying to connect to "localhost" will almost certainly use the first address first, which is the one workerd bound to, so things will just work fine.

That said, it turns out I actually fixed this on the Unix side a while ago: https://github.com/capnproto/capnproto/commit/f812158982f497e5eb0a8ca5ab286097b3d31367

But I didn't update async-io-win32.c++. If someone makes the same change to async-io-win32.c++ as was made to async-io-unix.c++ in that commit, it should allow workerd to bind to both IPs at once.

**Comment by 1000hz** [comment]
This should be fixed in the next release.
