### ISSUE TITLE
🐛 BUG: Logging a websocket message from a durable object logs a scary warning

### ISSUE THREAD

**Issue by threepointone** [cloudflare/workerd#1669]
### Which Cloudflare product(s) does this pertain to?

Wrangler core, Miniflare

### What version(s) of the tool(s) are you using?

wrangler@3.15.0

### What version of Node are you using?

v18.19.0

### What operating system and version are you using?

Mac OS 

### Observed behavior
I made a Durable Object, and connected to it with a websocket. The object responds to 'ping' with 'pong'. Pretty simple. Logging the event in the message handler logs a super scary warning 

```
<Formatting threw (Error: Failed to get the 'ports' property on 'MessageEvent': the property is not implemented.
    at MessageEvent.formatJsgResourceType (node-internal:internal_inspect:2188:31)
    at formatValue (node-internal:internal_inspect:660:49)
    at inspect (node-internal:internal_inspect:246:12)
    at formatWithOptionsInternal (node-internal:internal_inspect:2047:44)
    at formatWithOptions (node-internal:internal_inspect:1916:12)
    at formatLog (node-internal:internal_inspect:2136:16)
    at null.<anonymous> (file:///***/src/index.ts:48:13)>

```

### Expected behavior
It probably shouldn't log that warning? If that field hasn't been implemented yet it should probably just be ignored. 

### Steps to reproduce

- Checkout https://github.com/threepointone/scary-wrangler-error-log
-  `npm install && npm run dev`
- `open http://localhost:8787`
- look at the terminal console

### Please provide a link to a minimal reproduction

https://github.com/threepointone/scary-wrangler-error-log

**Comment by joelket23** [comment]
getting same issue 

<img width="973" alt="image" src="https://github.com/cloudflare/workerd/assets/82398173/eca614ad-a19f-4ada-83d4-05890218e1c7">

**Comment by MellowYarker** [comment]
When I run this on `wrangler@3.14.0` I get
```
MessageEvent {
  data: undefined,
  ports: undefined,
  source: undefined,
  lastEventId: undefined,
  origin: undefined
}
```

But it breaks on `wrangler@3.15.0` or greater.

@mrbbot it looks like you made a few changes to `console.log()` in both [workers-sdk](https://github.com/cloudflare/workers-sdk/pull/4235/files) and [workerd](https://github.com/cloudflare/workerd/pull/1343/files) that went into [that release](https://github.com/cloudflare/workers-sdk/releases/tag/wrangler%403.15.0). Sorry for the tag if you're already looking into it, just commenting since I was assigned at some point.
