### ISSUE TITLE
confused. what's the diff between workerd and miniflare?

### ISSUE THREAD

**Issue by ultperf** [cloudflare/workerd#207]
https://github.com/cloudflare/miniflare

1. which shld be supported more?
2. what's the direction of either?
3. will workerd have storage / redis etc kind of plugin like miniflare?

**Comment by kentonv** [comment]
Miniflare is specifically intended to be a testing environment. It simulates Cloudflare Workers locally, so that you can test and debug your code easily. In contrast, `workerd` is the underlying Workers engine which can be used for both testing and (self-hosted) production use cases.

Miniflare version 3 is built on top of `workerd`. Essentially, it adds a layer of automatic configuration and emulation of other Cloudflare services that aren't part of `workerd` itself (like Workers KV, R2, Cache API, etc.). Miniflare versions 1 and 2 predated the release of `workerd` and instead tried to emulate it on top of Node.js. Miniflare 3 provides a much more accurate simulation because it uses the real Workers engine code via `workerd`.
