### ISSUE TITLE
possible to use uwebsocket.js instead?

### ISSUE THREAD

**Issue by ultperf** [cloudflare/workerd#209]
possible to use uwebsocket.js instead?

if i would like to implement this for performance considerations, where should i replace the codes for workerd?

**Comment by kentonv** [comment]
No, this isn't possible.

µWebSockets is a Node extension. It is faster than other WebSocket implementations in Node presumably because it is implemented in native C++ code whereas other Node WebSocket implementations are written in JavaScript.

`workerd`, however, already uses a WebSocket implementation written in native C++. It probably already performs similarly to µWebSockets.

Even if µWebSockets is faster, it's unlikely that you'd be able to integrate it into `workerd`. `workerd` is based on a completely different I/O framework and event loop than Node. Porting I/O code designed for Node over to `workerd` would be a significant undertaking, similar to rewriting the code in a new programming language.

**Comment by ultperf** [comment]
@kentonv i missed this but it's an amazing answer with an amazing insights. thx.

after doing bazel run, i realised this code is... really intense in the programming knowledge implementation. it is still compiling in clang after 2 hours on my development laptop.

no idea what kind of magic is implemented into this.

**Comment by kentonv** [comment]
@ultperf To be honest, most of the compile time is building V8, the JavaScript engine. `workerd`'s own code is relatively small on top of that (but getting larger every day...).
