### ISSUE TITLE
🐛 Bug Report — Request Throws 'Invalid HTTP method' Error when Using Lowercase Method "patch"

### ISSUE THREAD

**Issue by Kynson** [cloudflare/workerd#2516]
### The Issue
`new Request('', {method: 'patch'})` unexpectedly throws error 'Invalid HTTP method string: patch' but `new Request('', {method: 'PATCH'})` works fine.

Minimal Reproducible Example: [Workers Playground](https://workers.cloudflare.com/playground#LYVwNgLglgDghgJwgegGYHsHALQBM4RwDcABAEbogB2+CAngLzbPYDqApmQNJQQBimYACFKNRHWABzdABYo6AFoQAygCYAXghEB2AAoAuFiw7deArCOq0J0uYpUat6PQFgAUAGF0VCOx-YAESgAZxh0YN55Kn0SDCw8AmISKjhgdgYAIigadgAPADoAK2CM0lQoMD9U9KycguKM9y8fPwhsABU6GHYYuBgYMCgAYwIo5EK4ADc4YKGEWAgAamB0XHB2d3dkACpttxJtkgABCC72XHZUEgBvAHkyQvYhiABfEgBRKkn97eQ3NzyYSQJAuqDg4AgNzcAEgdntoQdjvAEKkbgAldgARxA7GCrxICCxOLxMMRR2RqOun0mbz83wRh3JiEp71yTxA0G8zV8uXxz1ypMZhIgIAQVGCN10CHQwBC7AAPBjQt5guwAHwvQV-aEzOhUIaxdgQIYACwAFITsbiIAAaEh0u38gCUUOh0Ko7AA7iQMVa8WaAOQBu3XNIQE2rGIB+DGk0Bl5OmHQ4WiqjJL0+3FhcXsQO+PEBp1EGEvG1uF7F9xGZgmHj8QSWMT0KSyeRKNSaHS6JreXz+ILKiKc6KxQQJQikFJpTJhuD4QilWIVKrTjJkMDoMiNTy91odM69fqDEbD8bBbybNzXDJDGUxqBkCq8OgAfXn7Ay+gyqgADKoZNgP4AMyAdoGQ2jed6jI+gynC+qBgHAkglPoADaGRUKs7DFC+t7ADGGQALoQcAcDZC+KxrJUn61Bc9QlC8VbVrWZgNqI1gtnY7aOF2zDuEAA)

### Expected Behaviour
Both lowercase and uppercase method string should be supported (other methods support both lowercase and uppercase). 

### Suspected Cause
[L1000 of workerd/api/http.c++:](https://github.com/cloudflare/workerd/blob/615288376b21e40a1367282ae3970af3469531f1/src/workerd/api/http.c%2B%2B#L1000)
```c++
switch(method) {
                case kj::HttpMethod::GET:
                case kj::HttpMethod::POST:
                case kj::HttpMethod::PUT:
                case kj::HttpMethod::DELETE:
                case kj::HttpMethod::HEAD:
                case kj::HttpMethod::OPTIONS:
                  break;
                default:
                  JSG_FAIL_REQUIRE(TypeError, kj::str("Invalid HTTP method string: ", originalMethod));
}
```
Presumably, the switch statement will run when a lowercase method string is passed to the constructor as `tryParseHttpMethod` failed to parse the lowercase method string. Yet, `PATCH` is missing from the switch statement, so the error is thrown. I am not particularly familiar with C++ so I might be wrong with this.

**Comment by kentonv** [comment]
@harrishancock I don't suppose you remember why we're only case-insensitive for those six method names? Was this in the spec or something?

**Comment by jasnell** [comment]
If by spec you mean the http spec, there's nothing about special handling casing of only these basic 6 methods. Per the spec, all http methods are case sensitive. 

https://www.rfc-editor.org/rfc/rfc7231#section-4 
```
The method token is case-sensitive because it might be used as a gateway to object-based systems with case-sensitive method names.
```

So we really ought to be treating `get`, `post`, `put`, `delete`, `head`, and `options` as invalid also.

For the original ask here, `PATCH` is correct. `patch` is incorrect.

**Comment by kentonv** [comment]
I guess we're still violating spec either way in that if you specify `patch` lower-case, we throw an exception, whereas we should accept it. It seems better to uppercase it than to throw an exception I think.

Arguably we should actually expand the underlying KJ HTTP implementation to support arbitrary method names, rather than restricting them to an enum. I'm not excited about doing that, though, as:
* We've literally never heard anyone complain about wanting to use a method that's not on our list.
* There's some risk of security (request smuggling) bugs if someone defines a new method which, like `CONNECT`, doesn't use standard HTTP message framing.

So I'd be in favor of just upper-casing all methods.

**Comment by jasnell** [comment]
Marking as a feature request rather than a bug.

**Comment by jasnell** [comment]
This was closed automatically because the fix has been landed. The actual change will not go out to production for another week. Note that the change will become the default behavior for new workers deployed on-or-after Nov 14th (as currently planned). Workers using a compat date prior to that will need to opt in with a compatibility flag.
