### ISSUE TITLE
Add tests for workers-types that run in CI

### ISSUE THREAD

**Issue by Cherry** [cloudflare/workerd#2766]
Over the last year or so, there have been regular regressions or issues with workers-types that would have been caught with some testing and/or better vetting. 

workers-types is a huge cornerstone in the Cloudflare Workers development experience, with TypeScript being the recommended language across the docs, `npm create cloudflare`, etc. It would be really good to see this have a much more first-class experience and release/vetting process.

Examples:

- https://github.com/cloudflare/workerd/issues/2765
- https://github.com/cloudflare/workerd/issues/2174
- https://github.com/cloudflare/workerd/issues/1818
- https://github.com/cloudflare/workerd/issues/2211
- https://github.com/cloudflare/workerd/issues/2652
- https://github.com/cloudflare/workerd/issues/3186

There do appear to be some tests created in https://github.com/cloudflare/workerd/tree/main/types/test, but I'm not sure how often these run, or if they run in CI, or how much coverage they provide? It would be really nice if these ran regularly and perhaps even a diff of types changes were added into PRs so the types output can be analysed quickly and easily.

**Comment by penalosa** [comment]
This is a great callout. The types tests do run in CI, but they're more about testing the type generation logic rather than making sure the published types are what people expect. I think having a snapshot test of the type generation would be a great improvement, so the changes to the published types could be reviewed in PRs.
