### ISSUE TITLE
Feature request: RpcTarget wrapped in Proxy throws DataCloneError

### ISSUE THREAD

**Issue by rtbenfield** [cloudflare/workerd#3184]
An `RpcTarget` class instance that is wrapped in a `Proxy` throws the following runtime error when it is returned by an RPC call.

`DataCloneError: #<SimpleTarget> could not be cloned.`

```ts
export default class DefaultEntrypoint extends WorkerEntrypoint {
  override fetch(request: Request) {
    return Response.json({ hello: "world" });
  }

  // ✅ this is fine
  async workingRpcTarget() {
    return new SimpleTarget();
  }

  // ❌ this throws DataCloneError
  async brokenRpcTarget() {
    const target = new SimpleTarget();
    return new Proxy(target, {});
  }
}

class SimpleTarget extends RpcTarget {
  async targetCall() {
    return Promise.resolve({ hello: "world" });
  }
}
```

I found this while trying to extend our observability by capturing traces through `RpcTarget` instances. I have `WorkerEntrypoint` instrumented through `Proxy` thanks to the fix from #2291. The instrumentation is then checking if the return value of an RPC call is an instance of `RpcTarget` and attempts to wrap it in a `Proxy` to instrument those calls as well.

Could this be caused by the runtime failing to identify the `RpcTarget` inheritance of a `Proxy` and treating it as a plain object instead?

**Comment by jasnell** [comment]
I think this is more a case of the fact that the structured clone algorithm itself does not actually support `Proxy` objects. For instance, if you tried `structuredClone(new Proxy({}, {}))` in Workers or in Node.js etc you'd get a similar error: `structuredClone(new Proxy({}, {}))`. 

I think it would be possible for our serialization delegate to support `Proxy` as a new feature but we'd have to look at it a bit to confirm and not sure when we'd be able to implement. Going to mark this as a feature request.

**Comment by rtbenfield** [comment]
That makes sense 👍🏻  I didn't realize that an `RpcTarget` return value would need to be cloned and made the leap that it must be treating it as a plain object.

I can see this being an edge case for this type of decorator behavior that probably doesn't come up much. We've been leveraging RPC more, but unfortunately have given up our distributed tracing as a result. `RpcTarget` is especially interesting to me when returned by a DO and may likely incur network calls to another location. Just sharing the context in case it sparks any other ideas 🙂

**Comment by jasnell** [comment]
Internally we use structured clone in the communication protocol with the remote RPC target and have custom logic for handling more exotic objects like `RpcTarget`... it just needs to be taught what a `Proxy` is and how to handle it.

**Comment by jasnell** [comment]
@kentonv ... this is probably better suited for you. I can take a look at it but it'll be at least a couple of weeks before I could prioritize it.

**Comment by kentonv** [comment]
Right... so the problem is... various API times register themselves as serializable with a serializer callback. `RpcTarget` is among these, but its serializer is unusual: it doesn't actually serialize itself, it just writes out a stub pointing back to itself.

Now, normally, if you have a serializable type and you wrap it in a Proxy, the result is _not_ serializable. E.g. imagine you have a `Headers` object, and you wrap it in a `Proxy` that, say, rewrites headers on-demand. `Headers` itself is serializable, but this proxy clearly is _not_ serializable, because we have no way to serialize the rewrite logic. If we just serialized the underlying `Headers` and sent that, then the receiving end would receive an object that behaves differently from what the sender had sent.

But `RpcTarget` is a bit different in that we really only use `RpcTarget` as a _marker_ to indicate that we want to serialize the object by creating a stub. Technically, we could create a stub for _any_ object, we just refuse to do so if the object hasn't marked itself as `RpcTarget` because we don't want to expose something over RPC that wasn't intended to be.

But if a `Proxy` is wrapping an `RpcTarget`, probably we can presume it is intended to be available over RPC? I mean... I can't really say that with 100% certainty, you could have a generic proxy that is meant to wrap all kinds of objects and someone just happened to use it to wrap `RpcTarget` but for some reason it's totally inappropriate for it to be available over RPC. But that seems... unlikely enough that we shouldn't worry about it.

OK, so we should go ahead and write a stub pointing at the proxy. The other problem here though is that our serialization architecture is sort of... not designed this way. `serialize()` is a method on the `RpcTarget` itself, and it writes a stub pointing at itself. We need some entirely new path to say "hey serialize as if you were serializing yourself but actually point to this proxy object instead"... Not a huge problem, just annoying...

**Comment by kentonv** [comment]
Ughhhh, it looks like V8's ValueSerializer treats proxies as non-serializable without even calling the IsHostObject() callback, so we'll need another V8 patch to support this.

**Comment by kentonv** [comment]
OK, #3212 should fix this.

**Comment by rtbenfield** [comment]
> A `Proxy` can even be used to cause an object of class type that is not derived from `RpcTarget` behave as if it were, by overriding `getPrototypeOf()` to return `RpcTarget.prototype`. This is a feature, not a bug!

This is really interesting and I'm a fan. I can see some creative use cases coming out of this where the RPC methods are dynamic. Kind of an arbitrary example, but something like a D1 ORM over service binding where one could do `env.BINDING.open().tableName().select({ id: true })` and the implementation be a reusable `Proxy`. As with most Workers platform features, this my brain working on all the possibilities 😄 

Also, I'm always impressed by how fast y'all are able to tackle things like this. You're awesome 🙌🏻
