### ISSUE TITLE
Error thrown when feature testing for `duplex` request support, unusuable `ReadableStream` exposed

### ISSUE THREAD

**Issue by probablykasper** [cloudflare/workerd#391]
Apparently Workers exposes `ReadableStream` despite it being unusable, resulting in errors being thrown when feature testing.

From https://github.com/sindresorhus/ky/issues/453:

> Looks like this problem is caused by the fact that [we feature test](https://github.com/sindresorhus/ky/blob/740732c78aad97e9aec199e9871bdbf0ae29b805/source/core/constants.ts#L4-L22) for `duplex` support in the `Request` constructor and in order to do that, we call `ReadableStream()` if it's available. Prior to v0.31.2 we were only ever calling `ReadableStream()` if you used stream related features like `onDownloadProgress`. But now, we always test for `ReadableStream`'s existence no matter what, and if it's there, we use it. In other environments, that either succeeds or fails silently, and either way, Ky gets the information it needs. But in Workers, it throws an error.
> 
> Personally, I would argue that Workers shouldn't be exposing `ReadableStream` if it's unusable. So I'm going to close this for now. Feel free to propose a specific change to Ky if you think it's necessary. We could wrap our feature tests in a `try` / `catch` but that's not generally necessary given how they are written and it would hide legitimate bugs in our code, so I would prefer not to.

**Comment by KianNH** [comment]
It sounds like the issue is that they're checking if the ReadableStream constructor is available with `typeof globalThis.ReadableStream === 'function'` which will return true on Workers, even if the `streams_disable_constructors` compatibility flag is set, since that flag just determines if it'll throw a runtime error.

https://github.com/cloudflare/workerd/blob/ed4c67df1b231270410a72cb0161c203e55b0bb6/src/workerd/api/streams/readable.c%2B%2B#L525-L528

What could be done instead is check for the presence of something like `ReadableByteStreamController` in the global scope as that's only registered if the `streams_enable_constructors` flag is set.

https://github.com/cloudflare/workerd/blob/c0ea7352ffbef4e33da17127168b2b4ae3c6e1ac/src/workerd/api/global-scope.h#L357-L362

`typeof globalThis.ReadableByteStreamController === 'function'` would return `true` if the compatibility flag is set (and therefore ReadableStream constructors are available) and `false` if not (since it's undefined).

That workaround (hack) might only be applicable to Cloudflare Workers though. Wrangler does support conditional exports so it could be a check that's only implemented for the `workerd` export (https://developers.cloudflare.com/workers/wrangler/bundling/#conditional-exports), but that's up to the package author.

I'd let the runtime team comment first as they probably have a much cleaner solution.

`duplex` isn't implemented in Workers, so this would just stop it from throwing an exception and instead feature test as intended rather than add `duplex` support.

https://github.com/cloudflare/workerd/blob/c0ea7352ffbef4e33da17127168b2b4ae3c6e1ac/src/workerd/api/http.h#L562-L563

Just my two cents on the issue.

**Comment by jasnell** [comment]
Checking for the existence of `ReadableStreamDefaultController` is a good approach. There's really not going to be anything we can do about making `new ReadableStream()` work reliably as a check without requiring that compat flag. 

And yeah, we currently do not support the `duplex` option in `Request`.

**Comment by probablykasper** [comment]
Can't it behave like other runtimes? Is there any reason for `globalThis.ReadableStream` being a function when the `streams_enable_constructors` flag is not set?

**Comment by kentonv** [comment]
Workers has supported streaming HTTP requests and responses from the very beginning, but for a long time did not support constructing a `ReadableStream` using the constructor -- you could only get a `ReadableStream` by receiving an instance through other APIs, such as as part of a `Request` or `Response` object. This is why the class is exposed, but with no constructor.

Enabling the compatibility flag enables the constructor. We put this behind a flag because it is a new implementation of the stream classes and might not be bug-for-bug compatible with the old implementation.

The flag has been on by default since late November: https://developers.cloudflare.com/workers/platform/compatibility-dates/#streams-constructors

So, if you set your worker's compatibility date to a date after `2022-11-30`, or alternately set the flag `streams_enable_constructors`, then streams should be fully enabled. This seems like it would fix your problem?

**Comment by probablykasper** [comment]
That makes sense. Setting a later compatibility date does fix this, thank you!

**Comment by guest271314** [comment]
> or alternately set the flag streams_enable_constructors

How do we set that flag? I can't locate any documentation explaining how to do that https://github.com/cloudflare/workerd/issues/419, and that is one of the reasons I am experimenting with workerd.

**Comment by KianNH** [comment]
https://github.com/cloudflare/workerd/blob/1b5057f2bfcfedf146f6f79ff04e99903d55412b/src/workerd/io/compatibility-date.capnp#L114-L120

https://developers.cloudflare.com/workers/platform/compatibility-dates/

Check that your compatibility date is on or after the default date, or add it to your capnp config.

https://github.com/cloudflare/workerd/blob/1b5057f2bfcfedf146f6f79ff04e99903d55412b/src/workerd/server/workerd.capnp#L250-L256
