### ISSUE TITLE
🐛 Bug Report — Runtime APIs: No HTTP CONNECT support?

### ISSUE THREAD

**Issue by shaunco** [cloudflare/workerd#876]
I was making a pass at implementing a very simply http-proxy using the new [`connect()`](https://blog.cloudflare.com/workers-tcp-socket-api-connect-databases/) function and when I tried calling my worker (started with `wrangler dev` on wrangler v3.2.0) using `curl -x http://127.0.0.1:8787 https://www.example.com`, I got:

```
workerd/server/server.c++:2363: error: Uncaught exception: kj/compat/http.c++:6983: unimplemented: CONNECT is not implemented by this HttpService
```

I couldn't find anything in the Cloudflare Worker docs stating whether the CONNECT http method is supported or not in a worker, but given the new `connect()` method, it seems like it should be.

**Comment by kentonv** [comment]
Hi Shaun,

`CONNECT` is an unusual HTTP method since it isn't a simple request / response -- after the request and response, the socket changes modes and becomes a raw connection. This would require a dedicated API to handle correctly in a worker. It wouldn't work to just treat it like any other method. This is non-trivial to build so we've left it unsupported for now.

We haven't built this API yet, but we probably will in the future, along with adding support for Workers to receive incoming TCP connections (currently we only support outgoing connections).

I'm going to close this issue since we like to keep our issue tracker focused on short-term actionable bugs but this is something that will probably be supported in the long term.

**Comment by shaunco** [comment]
Thanks for the detailed reply. I was hopeful that al the work that went into handling websockets (and [post-worker eviction websocket flows](https://blog.cloudflare.com/workers-optimization-reduces-your-bill/)) would also have covered CONNECT with something like:
```ts
    // Connect to the requested destination
    const socket = request.fetcher?.connect(
      { hostname: url.hostname, port: +url.port },
      { secureTransport: "off", allowHalfOpen: false }
    )
    
    // Create a readable stream for the response
    const {readable, writable} = new TransformStream()
    socket.readable.pipeTo(writable)
    
    return new Response(readable, {status: 200, cf: {streaming: true}, headers: {}})
```

We can deploy our own Squid instance for now, but would love to see this support in the future! 

In the meantime, it would be great to update the [Limits](https://developers.cloudflare.com/workers/platform/limits/) and [Request](https://developers.cloudflare.com/workers/runtime-apis/request/#properties) pages to make it clear that `CONNECT` is not a supported HTTP method in Cloudflare Workers.

**Comment by shaunco** [comment]
@kentonv - just following up to make sure you see the request for docs to be updated so this limitation is more obvious to others who consider attempting the same thing.
