### ISSUE TITLE
Design question: Why do DurableObjects not need `waitUntil`?

### ISSUE THREAD

**Issue by nhynes** [cloudflare/workerd#877]
Or, alternatively, why do regular workers not have the same behavior as durable objects and pass draining the IoContext off to the next incoming request. The only concrete difference I have observed so far is that regular workers have a timeout limiter attached to them. I wonder if this a CF-internal design decision related to billing or architecture that the rest of shouldn't concern ourselves with? It would be helpful to understand the rationale!

**Comment by kentonv** [comment]
Hi Nick,

In short, Durable Objects don't have `waitUntil()` because it wouldn't do anything. A DO shuts down about 1 minute after the last client disconnects. `waitUntil()` extends a request's lifetime for 30 seconds. Since 30 seconds is less than 1 minute, using it wouldn't actually extend the lifetime at all. If it has no actual effect, then we can't reasonably expect anyone to use it, so we removed it.
